# Generated by Django 2.2.1 on 2019-09-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_posted']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='IMAGE',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pub_date',
            new_name='date_posted',
        ),
    ]
