# Generated by Django 2.2.1 on 2019-09-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0002_auto_20190906_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_update',
        ),
    ]
